spring:  
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-jin-dev
---

spring:
  profiles: test
  application:
    name: microservicecloud-config-jin-test
# 保存为utf-8
